# This is the configuration used to check the rubocop source code.

inherit_from: .rubocop_todo.yml

Documentation:
    Enabled: false

AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
    - 'config/initializers/new_framework_defaults.rb'
    - 'bin/*'
    - 'db/**/*'
  TargetRubyVersion: 2.3

EndOfLine:
  Enabled: false

Style/Encoding:
  EnforcedStyle: when_needed
  Enabled: true

Style/ClassAndModuleChildren:
  EnforcedStyle: nested

Style/FrozenStringLiteralComment:
  Enabled: false
  EnforcedStyle: always

Style/NumericLiterals:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/BlockComments:
  Description: 'Do not use block comments.'
  StyleGuide: '#no-block-comments'
  Enabled: false