language: ruby

rvm:
  - 2.3.3

cache: bundler

env:
  - DB=pgsql

services:
  - postgresql

before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database test;' -U postgres

test:
  adapter: postgresql
  database: travis_ci_test
  
script:
  - bundle exec rubocop
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake

addons:
    code_climate:
        repo_token: 8389ecc14a0756a14142623aa158328aaae5add4739b79cbed2e4e958509cd76
after_success:
  - bundle exec codeclimate-test-reporter